Update image check

diff --git a/.github/workflows/build-docker-image.yml b/.github/workflows/build-docker-image.yml
--- a/.github/workflows/build-docker-image.yml
+++ b/.github/workflows/build-docker-image.yml
@@ -66,6 +66,15 @@ jobs:
         run: |
           docker run --rm morphology-adaptive:local test -d /morphology-adaptive
 
+          # check that algovivo.so targets the correct architecture
+          expected_arch="${{ matrix.platform }}"
+          actual_arch=$(docker run --rm morphology-adaptive:local readlink /morphology-adaptive/algovivo.repo/build/native/algovivo.so | sed 's/algovivo\.\(.*\)\.so/\1/')
+          if [ "$actual_arch" != "$expected_arch" ]; then
+            echo "error: algovivo.so targets '$actual_arch', expected '$expected_arch'"
+            exit 1
+          fi
+          echo "algovivo.so targets $expected_arch"
+
       - name: Push image
         if: ${{ github.event_name == 'workflow_dispatch' && inputs.push == true }}
         uses: docker/build-push-action@v5
